apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: thesis
    role: frontend
    tier: angular
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: thesis
    role: frontend
    tier: angular