apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-contr
  labels:
    app: thesis
    role: frontend
    tier: angular
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thesis
        role: frontend
        tier: angular
    spec:
      containers:
      - name: thesis-web
        image: djob195/thesis-web
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80